name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Checkout Pac-Man repo
        uses: actions/checkout@v3
        with:
          repository: platane/pacman-contribution-graph
          path: pacman

      - name: Generate Pac-Man SVGs
        run: |
          cd pacman
          npm install
          npx pacman-contribution-graph --user murtazanoori --output ../output

      - name: Commit and push generated SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Update Pac-Man contribution graph" || echo "No changes to commit"
          git push
