name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clone Pac-Man repo
        run: |
          git clone https://github.com/platane/pacman-contribution-graph.git pacman
          cd pacman
          npm install

      - name: Generate Pac-Man SVGs
        run: |
          cd pacman
          npx pacman-contribution-graph --user murtazanoori --output ../output

      - name: Commit and push generated SVGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Update Pac-Man contribution graph" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
