name: Metrics
on:
  schedule: [{ cron: "0 */4 * * *" }]
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Isocalendar
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

      - name: Starred
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3

      - name: Stargazers
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes

      - name: Habits
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: America/Fortaleza

      - name: Followup
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes

      - name: Reactions
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/people.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      - name: Snippet
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/snippet.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_code: yes
          plugin_code_load: 400

      - name: Site
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/pagespeed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://murtazanoori.github.io

      - name: Lines
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes

      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_leetcode_user: murtazanoori

      - name: Introduction
        uses: lowlighter/metrics@latest
        with:
          user: murtazanoori
          filename: metrics/introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_introduction: yes
          plugin_introduction_title: "Welcome to My GitHub!"
          plugin_introduction_message: |
            I am a dedicated problem-solver with a strong focus on understanding complex challenges at their core.
            Passionate about helping others, I enjoy providing guidance and support in collaborative environments.
            With a keen interest in logical reasoning and a commitment to continuous learning through informative reading,
            I actively engage in sports, training in MMA and playing football. Thanks for visiting my profile!
